# Generated by Django 5.0.2 on 2024-03-21 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'عکس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(choices=[('سایز صفحه نمایش', 'صفحه نمایش'), ('دوربین', 'دوربین'), ('باتری', 'باتری'), ('آداپتور', 'شارژر'), ('رنگ', 'رنگ'), ('رم', 'رم'), ('پردازنده', 'پردازنده'), ('گرافیک', 'گرافیک'), ('حافظه داخلی', 'حافظه داخلی')], max_length=80, verbose_name='مشخصات')),
                ('feature_value', models.CharField(max_length=250, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'مشخصات',
                'verbose_name_plural': 'مشخصات',
                'unique_together': {('feature_key', 'feature_value')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, unique=True, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='ادرس')),
                ('image', models.ImageField(upload_to='images/', verbose_name='عکس کاور')),
                ('descriptions', models.TextField(default='No description provided', max_length=300, verbose_name='توضیح اجمالی محصول')),
                ('public', models.BooleanField(default=False, verbose_name='نمایش عمومی')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='Category.brand', verbose_name='برند')),
                ('category', models.ManyToManyField(to='Category.category', verbose_name='دسته بندی ها')),
                ('images', models.ManyToManyField(blank=True, to='BaseApp.image', verbose_name='عکس\u200cها')),
                ('features', models.ManyToManyField(related_name='product_features', to='BaseApp.productfeature', verbose_name='جزییات')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
