# Generated by Django 5.0.2 on 2024-03-03 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'اکانت', 'verbose_name_plural': 'اکانت\u200cها'},
        ),
    ]
